<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\EncDotNet.Iso8211\EncDotNet.Iso8211.csproj"/>
        <ProjectReference Include="..\..\src\EncDotNet.S57\EncDotNet.S57.csproj"/>
        <ProjectReference Include="..\..\src\EncDotNet.ChartViewer\EncDotNet.ChartViewer.csproj"/>
    </ItemGroup>

</Project>